export type RouteContext = "public" | "account" | "competition" | "blocked";

export type RouteDefinition = {
  id: string;
  path: string;
  context: RouteContext;
  purpose: string;
  states: readonly string[];
};

export const routeDefinitions: RouteDefinition[] = [
  { id: "auth.login", path: "/auth/login", context: "public", purpose: "登录入口", states: ["default", "loading", "error", "authMethod"] },
  { id: "onboarding.profile", path: "/onboarding/profile", context: "public", purpose: "基础资料完善", states: ["editing", "validating", "saving", "error"] },
  { id: "onboarding.survey", path: "/onboarding/survey", context: "public", purpose: "问卷采集", states: ["question", "saving", "completed", "error"] },
  { id: "onboarding.ready", path: "/onboarding/ready", context: "public", purpose: "进入平台前确认", states: ["ready"] },
  { id: "home", path: "/home", context: "public", purpose: "公共平台首页", states: ["guest", "noIdentity", "hasIdentity", "loading", "error"] },
  { id: "competitions.list", path: "/competitions", context: "public", purpose: "赛事发现", states: ["default", "filters", "empty", "loading", "error"] },
  { id: "competitions.mine", path: "/competitions/mine", context: "account", purpose: "我的赛事", states: ["none", "active", "ended", "loading", "error"] },
  { id: "competitions.detail", path: "/competitions/:competitionId", context: "public", purpose: "赛事详情", states: ["upcoming", "open", "registered", "ended", "unavailable"] },
  { id: "competitions.registration", path: "/competitions/:competitionId/registration", context: "account", purpose: "报名跳入与回流", states: ["notStarted", "externalInProgress", "submitted", "pending", "approved", "rejected", "failed"] },
  { id: "competition.workspace", path: "/competitions/:competitionId/workspace", context: "competition", purpose: "赛事上下文首页", states: ["locked", "pending", "active", "ended", "permissionRevoked"] },
  { id: "competition.team", path: "/competitions/:competitionId/workspace/team", context: "competition", purpose: "赛事团队", states: ["loading", "ready", "empty", "restricted"] },
  { id: "competition.resources", path: "/competitions/:competitionId/workspace/resources", context: "competition", purpose: "赛事资料", states: ["loading", "ready", "empty", "error"] },
  { id: "competition.resource", path: "/competitions/:competitionId/workspace/resources/:resourceId", context: "competition", purpose: "赛事资料详情", states: ["ready", "download", "error"] },
  { id: "workshop.home", path: "/competitions/:competitionId/workspace/workshop", context: "competition", purpose: "创赛工坊工作台", states: ["locked", "nextAction", "running", "waiting", "ended"] },
  { id: "workshop.project", path: "/competitions/:competitionId/workspace/workshop/project", context: "competition", purpose: "当前参赛项目", states: ["ready", "incomplete", "ended"] },
  { id: "workshop.compute", path: "/competitions/:competitionId/workspace/workshop/compute", context: "competition", purpose: "算力明细", states: ["ready", "empty"] },
  { id: "workshop.skills", path: "/competitions/:competitionId/workspace/workshop/skills", context: "competition", purpose: "技能矩阵", states: ["ready", "locked"] },
  { id: "workshop.skill", path: "/competitions/:competitionId/workspace/workshop/skills/:skillId", context: "competition", purpose: "技能入口", states: ["available", "locked", "completed"] },
  { id: "workshop.task.answer", path: "/competitions/:competitionId/workspace/workshop/tasks/:taskId/answer", context: "competition", purpose: "任务动态答题", states: ["editing", "incomplete", "error"] },
  { id: "workshop.task.review", path: "/competitions/:competitionId/workspace/workshop/tasks/:taskId/review", context: "competition", purpose: "生成确认", states: ["ready", "insufficientCompute", "error"] },
  { id: "workshop.task.progress", path: "/competitions/:competitionId/workspace/workshop/tasks/:taskId/progress", context: "competition", purpose: "任务运行进度", states: ["queued", "running", "failed", "completed"] },
  { id: "workshop.results", path: "/competitions/:competitionId/workspace/workshop/results", context: "competition", purpose: "工坊成果", states: ["empty", "ready", "loading"] },
  { id: "workshop.result", path: "/competitions/:competitionId/workspace/workshop/results/:resultId", context: "competition", purpose: "成果详情", states: ["draft", "teamVisible", "accepted", "archived"] },
  { id: "opportunities.list", path: "/opportunities", context: "public", purpose: "实习/就业机会发现", states: ["default", "filters", "empty", "loading", "error"] },
  { id: "opportunities.detail", path: "/opportunities/:opportunityId", context: "public", purpose: "机会详情", states: ["open", "closed", "alreadyApplied", "loading", "error"] },
  { id: "applications.list", path: "/applications", context: "account", purpose: "投递记录", states: ["empty", "submitted", "statusUnknown", "loading", "error"] },
  { id: "companies.list", path: "/companies", context: "public", purpose: "企业发现", states: ["default", "filters", "empty", "loading", "error"] },
  { id: "companies.detail", path: "/companies/:companyId", context: "public", purpose: "企业与资源关系", states: ["ready", "loading", "error"] },
  { id: "news.list", path: "/news", context: "public", purpose: "公告/资讯列表", states: ["default", "empty", "loading", "error"] },
  { id: "news.detail", path: "/news/:contentId", context: "public", purpose: "公告/资讯", states: ["ready", "loading", "error"] },
  { id: "courses.list", path: "/courses", context: "public", purpose: "课程发现/学习列表", states: ["all", "learning", "completed", "empty", "loading"] },
  { id: "courses.detail", path: "/courses/:courseId", context: "public", purpose: "课程详情", states: ["free", "entitlementRequired", "enrolled", "unavailable"] },
  { id: "courses.learn", path: "/courses/:courseId/learn", context: "account", purpose: "课程目录/学习", states: ["ready", "locked", "completed"] },
  { id: "courses.assessment", path: "/courses/:courseId/assessment", context: "account", purpose: "课程考试", states: ["ready", "submitting", "passed", "failed"] },
  { id: "courses.achievement", path: "/courses/:courseId/achievement", context: "account", purpose: "课程成果", states: ["inProgress", "claimable", "claimed"] },
  { id: "benefits.list", path: "/benefits", context: "public", purpose: "权益/兑换中心", states: ["eligible", "ineligible", "claimed", "expired", "empty"] },
  { id: "benefits.detail", path: "/benefits/:benefitId", context: "public", purpose: "权益详情", states: ["eligible", "ineligible", "claimed", "expired"] },
  { id: "benefits.wallet", path: "/benefits/wallet", context: "account", purpose: "我的权益/卡包", states: ["empty", "active", "used", "expired"] },
  { id: "growth.score", path: "/growth/score", context: "account", purpose: "学力值支撑信息", states: ["ready", "empty"] },
  { id: "assets.home", path: "/assets", context: "account", purpose: "长期资产总览", states: ["empty", "ready", "loading"] },
  { id: "assets.experiences", path: "/assets/experiences", context: "account", purpose: "赛事经历与项目摘要", states: ["empty", "ready", "loading"] },
  { id: "assets.experience", path: "/assets/experiences/:experienceId", context: "account", purpose: "赛事经历详情", states: ["ready", "syncing", "error"] },
  { id: "assets.learning", path: "/assets/learning", context: "account", purpose: "长期课程成果", states: ["empty", "ready", "loading"] },
  { id: "assets.results", path: "/assets/results", context: "account", purpose: "比赛/课程成绩", states: ["empty", "ready"] },
  { id: "assets.result", path: "/assets/results/:resultId", context: "account", purpose: "结果详情", states: ["ready", "pending", "invalid"] },
  { id: "assets.certificates", path: "/assets/certificates", context: "account", purpose: "证书列表", states: ["empty", "claimable", "claimed"] },
  { id: "assets.certificate", path: "/assets/certificates/:certificateId", context: "account", purpose: "证书详情", states: ["ready", "invalid", "revoked"] },
  { id: "assets.verification", path: "/assets/verification", context: "public", purpose: "可信成果验真", states: ["idle", "checking", "valid", "invalid", "error"] },
  { id: "stories.list", path: "/stories", context: "public", purpose: "赛友内容", states: ["default", "filters", "empty"] },
  { id: "stories.detail", path: "/stories/:storyId", context: "public", purpose: "赛友/公众号内容详情", states: ["internal", "external"] },
  { id: "stories.submit", path: "/stories/submit", context: "account", purpose: "投稿", states: ["editing", "submitting", "success", "error"] },
  { id: "support.home", path: "/support", context: "public", purpose: "帮助与客服", states: ["ready", "error"] },
  { id: "support.chat", path: "/support/chat", context: "account", purpose: "客服会话", states: ["ai", "humanRequested", "externalWeCom"] },
  { id: "me.home", path: "/me", context: "account", purpose: "我的", states: ["ready", "incompleteProfile"] },
  { id: "me.profile", path: "/me/profile", context: "account", purpose: "个人资料", states: ["view", "edit", "saving", "error"] },
  { id: "me.resume", path: "/me/resume", context: "account", purpose: "长期简历", states: ["empty", "ready"] },
  { id: "me.resume.strengths", path: "/me/resume/strengths", context: "account", purpose: "个人优势", states: ["edit", "saving"] },
  { id: "me.resume.education", path: "/me/resume/education", context: "account", purpose: "教育经历", states: ["list", "edit", "saving"] },
  { id: "me.accounts", path: "/me/accounts", context: "account", purpose: "第三方账号", states: ["list", "binding", "success", "error"] },
  { id: "me.subjects", path: "/me/subjects", context: "account", purpose: "主体管理（语义待确认）", states: ["empty", "list", "adding", "scanning"] },
  { id: "me.notifications", path: "/me/notifications", context: "account", purpose: "通知中心", states: ["all", "unread", "empty", "loading"] },
  { id: "me.notification", path: "/me/notifications/:notificationId", context: "account", purpose: "通知详情", states: ["read", "unread"] },
  { id: "legal.user", path: "/legal/user-agreement", context: "public", purpose: "用户协议", states: ["ready"] },
  { id: "legal.privacy", path: "/legal/privacy", context: "public", purpose: "隐私政策", states: ["ready"] },
  { id: "about", path: "/about", context: "public", purpose: "关于", states: ["ready"] },
  { id: "tasks.reserved", path: "/tasks", context: "blocked", purpose: "任务专区保留位", states: ["blockedByDecision"] },
];

export const candidatePrimaryNavigation = [
  { label: "首页", to: "/home" },
  { label: "赛事", to: "/competitions" },
  { label: "机会", to: "/opportunities" },
  { label: "我的", to: "/me" },
] as const;
